#!/usr/bin/env python
import psycopg2
from psycopg2 import extras
from sys import argv
from textwrap import dedent
from contextlib import contextmanager

class ExpenseData:

    @contextmanager
    def _database_connect(self):
        connection = psycopg2.connect(dbname='expense')
        try:
            with connection:
                yield connection
        finally:
            connection.close()

    def _display_expenses(self, expenses):
        results = []
        for expense in expenses:
            columns = [
                str(expense['id']).rjust(3),
                str(expense['created_on']),
                str(expense['amount']).rjust(12),
                str(expense['memo'])
            ]
            results.append(" | ".join(columns))
        return results


    def list_expenses(self):
        with self._database_connect() as connection:
            with connection.cursor(cursor_factory=extras.DictCursor) as cursor:
                cursor.execute('SELECT * FROM expenses ORDER BY created_on;')
                expenses = cursor.fetchall()

        expense_count = len(expenses)
        if expense_count == 0:
            print('No expenses to see yet ...')
            return
        if expense_count == 1:
            expense_description = "There is 1 expense. \n"
        else:
            expense_description = f"There are {expense_count} expenses. \n"

        results = self._display_expenses(expenses)
        # print(f'TEST {expenses} \n NEXT: {results}')
        total_amount = 'TODO'

        print(expense_description)
        print('\n'.join(results))
        print("\n--------------------------------------------------")
        print(f"\nTotal {str(total_amount).rjust(25)}") # TODO


    def add_expense(self, amount, memo):
         with self._database_connect() as connection:
            with connection.cursor(cursor_factory=extras.DictCursor) as cursor:
                cursor.execute('''INSERT INTO expenses (amount, memo, created_on)
                VALUES (%s, %s, NOW());''', (float(amount), memo, ))


    def clear(self):
        with self._database_connect() as connection:
            with connection.cursor(cursor_factory=extras.DictCursor) as cursor:
                cursor.execute('DELETE FROM expenses;')

                print('All expenses have been deleted')


    def delete_expense(self, number):
        with self._database_connect() as connection:
            with connection.cursor(cursor_factory=extras.DictCursor) as cursor:
                cursor.execute('SELECT * FROM expenses WHERE id = %s;', (int(number),)) 
                expense = cursor.fetchall()

                cursor.execute('DELETE FROM expenses WHERE id = %s;', (int(number),))


        columns = self._display_expenses(expense)
        print(f"""The following expense has been deleted:\n {" | ".join(columns)}""")

    def search_expense(self, query):
        query = f'%{query}%'
        with self._database_connect() as connection:
            with connection.cursor(cursor_factory=extras.DictCursor) as cursor:
                cursor.execute("SELECT * FROM expenses WHERE memo ILIKE %s;", (query,) ) 
                expenses = cursor.fetchall()

        result_total = len(expenses)

        results = self._display_expenses(expenses)

        if result_total == 1:
            description = 'There is 1 expense.'
        else:
            description = f'There are {result_total} expenses.'

        print(f"""{description} \n{'\n'.join(results)}""") 


    def add_rows(self):
        with self._database_connect() as connection:
            with connection.cursor(cursor_factory=extras.DictCursor) as cursor:
                cursor.execute('''INSERT INTO expenses
                (amount, memo, created_on) VALUES
                (5.99, 'coffee', NOW() ),
                (123.45, 'subscription', NOW()),
                (67, 'your mom', NOW());'''
                )


class CLI():
    def __init__(self):
        self.expense_instance = ExpenseData()

    # IF no values in arg_list
    def display_help(self):
        prompt = """
        An expense recording system

        Commands:

        add AMOUNT MEMO [DATE] - record a new expense
        clear - delete all expenses
        list - list all expenses
        delete NUMBER - remove expense with id NUMBER
        search QUERY - list expenses with a matching memo field
        """

        print(dedent(prompt))


    def run(self, arg_list):

        argument_length = len(arg_list)

        if argument_length == 0: # ./expense
            command = None

        else:
            command = arg_list[0]

            match command: # TODO
                case 'clear':
                    confirm = input('This will remove all expenses.' \
                                    ' Are you sure? (enter y to confirm)')
                    if confirm == 'y':
                        self.expense_instance.clear()

                case 'list':
                    self.expense_instance.list_expenses()

                case 'reset':
                    self.expense_instance.add_rows()

                case "delete":
                    if argument_length == 2: 
                        argument = arg_list[1]
                        if argument.isnumeric():
                            self.expense_instance.delete_expense(argument)
                    else:
                        print('Oops! Please enter a valid number corresponding '\
                        'to the id of the expense you are looking for.')

                case "search":
                    if argument_length == 2:
                        argument = arg_list[1]
                        self.expense_instance.search_expense(argument)
                    else:
                        print("Oops! You must provide a memo.")
                        return

                case "add":
                    if argument_length == 3:
                        amount = arg_list[1]
                        try: 
                            float(amount)
                        except ValueError: 
                            print('You must provide a numeric' \
                            ' amount for the 2nd argument (amount).')
                            return
                        if float(amount) < 0:
                            print('You must provide a non negative number.')
                            return
                        memo = arg_list[2]

                        self.expense_instance.add_expense(amount, memo)
                    else:
                        print("Oops! You must provide an amount and memo.")
                        return

                case _:
                    self.display_help()


if __name__ == "__main__":
    cli_instance = CLI()
    cli_instance.run(argv[1:])